# Generated by Django 2.0.7 on 2019-10-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('middle_initial', models.CharField(max_length=1)),
                ('last_name', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('role', models.CharField(choices=[('PS', 'President'), ('PR', 'Provost'), ('DH', 'Dean / Department Head'), ('AD', 'Assistant Dean'), ('TB', 'Trustee Board Member'), ('AF', 'Adjunct Faculty Member'), ('TF', 'Tenured Faculty Member'), ('TA', 'Teacher Assistant'), ('AM', 'Administrator')], max_length=2)),
                ('department', models.IntegerField()),
                ('street_address', models.TextField()),
                ('city', models.TextField()),
                ('us_state', models.TextField(verbose_name='state')),
                ('zip_code', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('country_code', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('ssan', models.CharField(max_length=12)),
            ],
        ),
    ]
