# Generated by Django 2.0.7 on 2019-10-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_logs',
            old_name='_end',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event_logs',
            old_name='_start',
            new_name='start',
        ),
        migrations.AlterField(
            model_name='event_logs',
            name='event_date',
            field=models.TextField(),
        ),
    ]
