# Generated by Django 2.0.7 on 2019-11-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='country_code',
            field=models.IntegerField(default=1),
        ),
    ]
