# Generated by Django 2.0.7 on 2019-11-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20191102_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='height',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
