# Generated by Django 2.0.7 on 2019-10-27 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_auto_20191015_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action_Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned', models.TextField()),
                ('desc', models.TextField()),
                ('exp_date', models.TextField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Staff')),
            ],
        ),
    ]
