# Generated by Django 2.0.7 on 2019-10-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action_items',
            name='task_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('IN_PROGRESS', 'IN PROGRESS'), ('COMP', 'COMPLETE')], default='NEW', max_length=11),
        ),
    ]
