# Generated by Django 2.0.7 on 2019-10-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_items', '0002_action_items_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action_items',
            name='task_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('IN PROGRESS', 'IN PROGRESS'), ('COMP', 'COMPLETE')], default='NEW', max_length=11),
        ),
    ]
